### ISSUE TITLE
Integrate map browser into atlasbiowork.com

### ISSUE THREAD

**Issue by managingwholes** [Soil-Carbon-Coalition/map-browser#1]
Integrate map browser into atlasbiowork app (configuration object, etc.)

Query to combine observations.json and sites.geojson into one filterable geojson file for map layers

**Comment by sheppard** [comment]
I added a read-only geometry field to the existing `ObservationSerializer` so you can start testing this out with URL based filters:
```
/observations.geojson?type_id=3
/observationtypes/3/observations.geojson
```
Eventually we might want separate serializers for map observations versus editable observations, but this will work for now.

**Comment by managingwholes** [comment]
I pulled your changes and deployed .07. Awesome, thanks.
